services:
  php:
    build:
      context: ./
      args:
        XDEBUG_INSTALL: 0
    container_name: php-commission-calculator
    volumes:
      - ./app:/var/www
    environment:
      XDEBUG_CONFIG: client_host=172.17.0.1 client_port=9004
      PHP_IDE_CONFIG: serverName=commission-calculator